name: Lint, build, test, deploy
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # Required by playwrgith
          node-version: "16"
          cache: "yarn"
      # This should not be necessary, but for some reason it is
      - run: npm install -g yarn
      # This is needed when playwright is used in tests #70
      - run: npx playwright install-deps
      - run: yarn --version
      - run: yarn install
      - name: Start dev server
        run: nohup yarn start &
      - name: Run atomic-server docker image in background (for testing)
        run: nohup docker run -p 80:80 -p 443:443 -v atomic-storage:/atomic-storage joepmeneer/atomic-server --initialize &
      - run: yarn lint-fix
      - run: yarn build
      - run: yarn test
      - run: yarn typedoc
      - name: Deploy production 🚀
        if: ${{github.ref == 'refs/heads/main'}}
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: data-browser/publish # The folder the action should deploy.
      - name: Deploy staging 🚀
        if: ${{github.ref != 'refs/heads/main'}}
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: data-browser/publish # The folder the action should deploy.
          target-folder: staging
